# Generated by Django 5.0 on 2023-12-14 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.IntegerField(choices=[(0, 'Withdraw Cash'), (1, 'Withdraw Card'), (2, 'Withdraw Gift Card')])),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.document')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
